name = "Statlib"
defaultTargets = ["Statlib"]
version = "0.1.0"
keywords = ["probability", "statistics", "lean"]
packagesDir = ".lake/packages"
lintDriver = "batteries/runLinter"

[leanOptions]
autoImplicit = true
# Enable all mathlib linters: automatically matches what mathlib uses.
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "dd56d02cb7a58fa066c4a2c7fddec3cbb59ae8df"

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso"
rev = "main"

[[lean_lib]]
name = "Statlib"
